services:
  docker-server:
    environment:
      DOCKER_TLS_CERTDIR: ""
    ports: !reset []
    command: !override
      - dockerd
      - --group
      - "1000"
      - --host=unix:///var/run/docker.sock
      - --host=tcp://0.0.0.0:${DOCKER_SERVER_SOCKETDUCT_PORT:-2375}
      - --registry-mirror=http://${REGISTRY_CACHE_HOST:-registry-cache}:${REGISTRY_CACHE_PORT:-5000}
      - --insecure-registry=${REGISTRY_CACHE_HOST:-registry-cache}:${REGISTRY_CACHE_PORT:-5000}
